### ISSUE TITLE
Feature request : File rename

### ISSUE THREAD

**Issue by ploufs** [jaymoulin/docker-rpi-plex-video-converter#1]
Remove in filename extra text.

Original filename: 
[source] {show name}.{S01}.{E02}{extra text}.avi
result:
{show name}.{S01}.{E02}.mp4

**Comment by jaymoulin** [comment]
Not the purpose of this project. The purpose is only to convert files and not renaming. This won't work neither with movie nor video clips nor TV show episodes not named like the specified string format. Too specific.

I suggest you to fork the project to implement this feature for your use case.
