### ISSUE TITLE
[FR] Add optional Parameter to delete the orginal file

### ISSUE THREAD

**Issue by reloxx13** [jaymoulin/docker-rpi-plex-video-converter#5]
I got a huge Media DB. If i convert all now,   
the HDD will be full before all the conversion completed.

Thats why it would be nice to add another parameter to delete the orginal file after successfull converting.

Thank you for the image!

**Comment by jaymoulin** [comment]
Thanks for your report.

I don't get your problem. Videos are converted one by one in alphanumerical order and deleted after a successful conversion. Your HDD just need space for your first video file.

**Comment by jaymoulin** [comment]
References : 
- https://github.com/jaymoulin/docker-rpi-plex-video-converter/blob/master/convert.sh#L11
- https://github.com/jaymoulin/docker-rpi-plex-video-converter/blob/master/convert.sh#L17
